### ISSUE TITLE
What is the AXI format for?

### ISSUE THREAD

**Issue by Qix-** [fogleman/svg2axi#1]
Hey Michael, long time follower/lurker. Just noticed this pop up in my feed and was curious about what the AXI format was but can't find any information aside from (seemingly unrelated) information about an old file management format.

I'm always on the lookout for new formats like this so figured I'd ask :) Is it related to formlabs specifically, perhaps?

**Comment by fogleman** [comment]
It's for my pen plotter library: https://github.com/fogleman/axi

It's very simple. Just a plain text file with one path per line where each path is a list of space-separated X,Y points.
